-- Use this SQL in the Supabase SQL Editor to create the required table

CREATE TABLE IF NOT EXISTS trades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    direction TEXT NOT NULL,
    entry_low FLOAT8 NOT NULL,
    entry_high FLOAT8 NOT NULL,
    take_profits JSONB NOT NULL,
    stop_loss FLOAT8 NOT NULL,
    status TEXT DEFAULT 'open',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    closed_at TIMESTAMPTZ,
    pnl FLOAT8 DEFAULT 0,
    notes TEXT
);

-- Enable Realtime for this table (optional, but good for dashboards)
ALTER TABLE trades REPLICA IDENTITY FULL;
